import subprocess
import sys


def installPackages(pacakge):
    subprocess.check_call([sys.executable, "-m", "pip", "install", pacakge])


if __name__ == '__main__':
    installPackages("asposepdfcloud == 20.12.0")
    installPackages("attrs == 20.3.0")
    installPackages("boto3 == 1.17.35")
    installPackages("botocore == 1.20.35")
    installPackages("certifi == 2020.12.5")
    installPackages("chardet == 4.0.0")
    installPackages("ci-info == 0.2.0")
    installPackages("click == 7.1.2")
    installPackages("colordict == 1.2.4")
    installPackages("configobj == 5.0.6")
    installPackages("configparser == 5.0.2")
    installPackages("decorator == 4.4.2")
    installPackages("EasyProcess == 0.3")
    installPackages("et-xmlfile == 1.0.1")
    installPackages("etelemetry == 0.2.2")
    installPackages("filelock == 3.0.12")
    installPackages("future == 0.18.2")
    installPackages("httplib2 == 0.19.0")
    installPackages("idna == 2.10")
    installPackages("iniconfig == 1.1.1")
    installPackages("isodate == 0.6.0")
    installPackages("jdcal == 1.4.1")
    installPackages("jmespath == 0.10.0")
    installPackages("language-check == 1.1")
    installPackages("linecache2 == 1.0.0")
    installPackages("lxml == 4.6.2")
    installPackages("networkx == 2.5")
    installPackages("nibabel == 3.2.1")
    installPackages("nipype == 1.6.0")
    installPackages("numpy == 1.20.1")
    installPackages("opencv-python == 4.5.1.48")
    installPackages("openpyxl == 3.0.6")
    installPackages("packaging == 20.9")
    installPackages("pandas == 1.2.3")
    installPackages("pathlib == 1.0.1")
    installPackages("pdfminer == 20191125")
    installPackages("Pillow == 8.1.1")
    installPackages("pluggy == 0.13.1")
    installPackages("protobuf == 3.14.0")
    installPackages("prov == 2.0.0")
    installPackages("py == 1.10.0")
    installPackages("pycryptodome == 3.10.1")
    installPackages("pydot == 1.4.2")
    installPackages("PyMuPDF == 1.18.9")
    installPackages("pyparsing == 2.4.7")
    installPackages("pyPdf == 1.13")
    installPackages("PyPDF2 == 1.26.0")
    installPackages("PyPDF4 == 1.27.0")
    installPackages("pytesseract == 0.3.7")
    installPackages("pytest == 6.2.2")
    installPackages("pytest-html == 3.1.1")
    installPackages("pytest-metadata == 1.11.0")
    installPackages("python-dateutil == 2.8.1")
    installPackages("pytz == 2021.1")
    installPackages("PyVirtualDisplay == 2.1")
    installPackages("pyxnat == 1.4")
    installPackages("rdflib == 5.0.0")
    installPackages("reportlab == 3.5.62")
    installPackages("requests == 2.25.1")
    installPackages("s3transfer == 0.3.6")
    installPackages("scipy == 1.6.1")
    installPackages("selenium == 3.141.0")
    installPackages("simplejson == 3.17.2")
    installPackages("six == 1.15.0")
    installPackages("toml == 0.10.2")
    installPackages("traceback2 == 1.4.0")
    installPackages("traits == 6.2.0")
    installPackages("unittest2 == 1.1.0")
    installPackages("urllib3 == 1.26.3")
    installPackages("xlrd == 1.2.0")
    installPackages("XlsxWriter == 1.3.7")
    installPackages("xlwt == 1.3.0")
    installPackages('xlsxwriter')
    installPackages('xlrd')
